### ISSUE TITLE
Login screen text is invisible in dark mode

### ISSUE THREAD

**Issue by murchu27** [Jeoxs/khanos#12]
I haven't reviewed the code, but I can see that one effect of switching to Dark Mode is inverting black text to white text throughout the whole app.

This works well in most places, but it makes the login screen text invisible, as the background that it sits against stays white, even in dark mode (see screenshot below).

Expected behaviour is that, when in dark mode, either the login screen text should either be left as black, or the background should change to black, so that text is visible.

![Screenshot_20210828-074855_1](https://user-images.githubusercontent.com/24554361/131209473-70997ac9-7a25-4d0d-8db2-603114934bdc.jpg)

**Comment by Jeoxs** [comment]
Thank you for the report. I've published a new release with a fix for this. You can download it on the Latest Release page or wait for Google Play's Update rollout

**Comment by murchu27** [comment]
Works perfectly on my side, thanks!
