### ISSUE TITLE
Error After login

### ISSUE THREAD

**Issue by bobylapointe63** [Jeoxs/khanos#15]
I have the same error After login
![Screenshot_2021-09-01-07-07-01-69_e437587d8f40808310a605e2387c548b](https://user-images.githubusercontent.com/5341182/131615884-ceeb91b0-5cb6-4a3b-8748-23b1e01010ba.jpg)
Best regard

**Comment by bobylapointe63** [comment]
everything is nikel from the admin account only, on the other accounts you can just connect but not navigate in the projects

**Comment by bobylapointe63** [comment]
actually I have not verified this hypothesis ... for the moment I have this
problem on my directories .... I try during the day and I will keep you
informed.  cordially

Le jeu. 2 sept. 2021 à 01:52, José Aponte ***@***.***> a
écrit :

**Comment by bobylapointe63** [comment]
I have the same on other users ...

**Comment by Jeoxs** [comment]
I'll make some tests on my side in order to replicate the issue and fix this

**Comment by Jeoxs** [comment]
Good News: I found the cause of the error. The culprit is the provider API Method I use to get Project Users. I'll fix this by adding the access and permissions feature for users.

**Comment by Jeoxs** [comment]
I added user permissions validation for projects. I made some test with a normal user with "project-viewer" permission on certain projects. It seems to work. It would mean a lot if you could try it out. You can find the newest release on the releases section. Google play update will come soon
