### ISSUE TITLE
Login requirements?

### ISSUE THREAD

**Issue by lorddoumer** [Jeoxs/khanos#20]
Hello,
are there any special login-requirements to use Khanos? Always getting "unknown error" when I try to login with an flawlessly working Kanboard-instalation (current version 1.2.20, current app-version from the Playstore) :-(

**Comment by axb21** [comment]
If you have 2FA turned on you might want to check out #11

**Comment by lorddoumer** [comment]
Thanks, but 2FA is not enabled :(

**Comment by Jeoxs** [comment]
> Thanks, but 2FA is not enabled :(

Hello @lorddoumer, thank you for using Khanos. I'll need more information about your issue. Do you have a custom role for your user or any custom auth setting you might consider? Any info would be great for me in order to replicate the problem

**Comment by lorddoumer** [comment]
@Jeoxs no, just using the build in roles (manager, participant, viewer) and the default login (username + password) on an Linux server with Apache running. Set up some users and boards and installed a few plugins: 
- Gantt
- Highlight Code Syntax
- Milestone
- Time Tracking Editor
- Bigboard
- Markdown Plus
- Taglist
What other information could be helpful? If I can provide anything, please let me know :)

**Comment by arteteco** [comment]
EDIT: I solved it. My website is at `https://mywebsite.com/kanboard`, but the app didn't take it unless it was as `https://www.mywebsite.com/kanboard`. The `www` made it work, hope it helps



Same problem here. 100% password is alright, very similar setting to @lorddoumer 

No special role
login as username and password (no 2fa)

Could it make a difference that the kanboard is in a subfolder and not in the root of a domain-subdomain? is like, https://mysite/kanboard

plugins:

* Customizer
* Essential theme
* EnableAttachmentRenaming
* Telegram
* Wiki
* KanboardSearchPlugin
* Gantt
* Calendar

**Comment by arteteco** [comment]
Same problem here. 100% password is alright, very similar setting to @lorddoumer 

No special role
login as username and password (no 2fa)

plugins:

* Customizer
* Essential theme
* EnableAttachmentRenaming
* Telegram
* Wiki
* KanboardSearchPlugin
* Gantt
* Calendar
